### ISSUE TITLE
URP - not showing anything in VisionOS

### ISSUE THREAD

**Issue by antoniohof** [keijiro/SplatVFX#3]
Hi,

I'm trying to make it work with VisionOS but it doesn't show anything, even though shadergraph was supposed to be compatible.

Have you tested in this platform?

Best,

**Comment by keijiro** [comment]
I think VFX Graph is not supported on it.

> Have you tested in this platform?

Unfortunately, no because it's still in the closed testing phase (I can't test it).

**Comment by keijiro** [comment]
I close this issue at the moment as by-design. I'll reopen if the platform supports VFX Graph.

**Comment by andybak** [comment]
I already added some background info for @antoniohof on this issue: https://github.com/aras-p/UnityGaussianSplatting/issues/71#issuecomment-1802082754
