### ISSUE TITLE
Inquiry about Setting Up Disintegration Effect Simulation

### ISSUE THREAD

**Issue by PockPocket** [keijiro/SplatVFX#5]
Hello Keijiro,

I hope this message finds you well. I've been exploring the simulation setup to recreate the disintegration effect featured in the second video highlighted on the GitHub page. Despite attempting to implement it within both the HDRP and VFX projects (recognizing these as distinct projects), I'm struggling to connect the bicycle.splat file to function with the disintegration "VFX" effect graph and to visualize it within the scene function.

I would greatly appreciate any guidance or assistance you could provide on this matter.

Warm regards,
Mathieu

**Comment by keijiro** [comment]
You should put `bicycle.splat` into `VFX/Assets` before opening the project at the first time. Unity Editor will remove the metadata file (`.meta`) when the file body is missing.

**Comment by PockPocket** [comment]
I'm back at it with this project and I can't seem to remember how I was managing to import and convert my .ply to .splat directly in this Unity project. I thought I remembered that I could manually change the .ply to .splat by renaming it in the file explorer before opening the Unity project but now this creates crazy glitches when adding it to the scene and pressing play:
![image](https://github.com/keijiro/SplatVFX/assets/73412598/d71f320c-3a84-4048-b864-85d2b86f4882)

converting my .ply to .splat using https://antimatter15.com/ or polycam website
creates these weird large circles and are never as clean as the Bicycle example:
![image](https://github.com/keijiro/SplatVFX/assets/73412598/b853ecc2-fd1f-4cb4-a08c-cdbdcd0204ab)

Any idea of what I'm doing wrong here ? the only .splat that works correctly is the bicycle.splat - all my other .ply creates those glitches in unity and big large circles when converted in https://antimatter15.com/
