### ISSUE TITLE
The disintegration VFX doesn't work in a HDRP project

### ISSUE THREAD

**Issue by PockPocket** [keijiro/SplatVFX#8]
You should put `bicycle.splat` into `VFX/Assets` before opening the project at the first time. Unity Editor will remove the metadata file (`.meta`) when the file body is missing.

_Originally posted by @keijiro in https://github.com/keijiro/SplatVFX/issues/5#issuecomment-1837046200_

Hi Keijiro, 

I'm trying to add this SplatVFX repository to an existing HDRP project but can't make it work, the bicycle scene is working but not the vfx desintegration effect.. and the fps is surprisingly low (6fps in play mode on with Nvidia RTX A6000 48Go).

The only way I can make the VFX work is when I create a new hdrp project directly from this repository.

Do you know if there's a way to add the repository of SplatVFX in an existing HDRP project with the desintegration VFX that is active ? 

All the best, 
Mathieu

**Comment by keijiro** [comment]
The disintegration is controlled by the timeline. You have to recreate it in your scene.
