### ISSUE TITLE
Sample VFX shader graph

### ISSUE THREAD

**Issue by BarnabasTakacs** [keijiro/SplatVFX#9]
Wonderful work, congratulations.

Would you please add some example shader graphs for the VFXs you show in the video? The repo does not contain just the 3DGS rendering.
Thank you in advance

**Comment by keijiro** [comment]
It's contained in the `VFX` directory.
By the way, it's implemented as a VFX Graph, not as Shader Graph.

**Comment by BarnabasTakacs** [comment]
Thank you, indeed so. My mistake.
